export class SentenceModel {
  private sentences: string[] = [
    'The quick brown fox jumps over the lazy dog.',
    'Every artist was first an amateur.',
    'Persistence can change failure into extraordinary achievement.',
    'Imagination is more important than knowledge.',
    'Do not watch the clock; do what it does. Keep going.',
    'Life is 10% what happens to us and 90% how we react to it.',
    'The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.',
    'Keep your face always toward the sunshine - and shadows will fall behind you.',
    'It is during our darkest moments that we must focus to see the light.',
    'The only limit to our realization of tomorrow will be our doubts of today.',
    'The only way to do great work is to love what you do.',
    "Change your life today. Don't gamble on the future, act now, without delay.",
    'Life is really simple, but we insist on making it complicated.',
    'Perfection is not attainable, but if we chase perfection we can catch excellence.',
    'Life is a succession of lessons which must be lived to be understood.',
    'It does not matter how slowly you go as long as you do not stop.',
    'Our lives begin to end the day we become silent about things that matter.',
    'Do not go where the path may lead, go instead where there is no path and leave a trail.',
    'You will face many defeats in life, but never let yourself be defeated.',
    'The greatest glory in living lies not in never falling, but in rising every time we fall.',
    "In the end, it's not the years in your life that count. It's the life in your years.",
    'Life is either a daring adventure or nothing at all.',
    'You must be the change you wish to see in the world.',
    'What you get by achieving your goals is not as important as what you become by achieving your goals.',
    "Believe you can and you're halfway there.",
    'When you reach the end of your rope, tie a knot in it and hang on.',
    'Tell me and I forget. Teach me and I remember. Involve me and I learn.',
    'The best time to plant a tree was 20 years ago. The second best time is now.',
    'An unexamined life is not worth living.',
    "Your time is limited, don't waste it living someone else's life.",
    "I have learned over the years that when one's mind is made up, this diminishes fear.",
    'Either you run the day, or the day runs you.',
    "Whether you think you can or you think you can't, you're right.",
    'The only person you are destined to become is the person you decide to be.',
    "Go confidently in the direction of your dreams! Live the life you've imagined.",
    'Life is 10% what happens to me and 90% of how I react to it.',
    "The most common way people give up their power is by thinking they don't have any.",
    'The mind is everything. What you think you become.',
    'The best revenge is massive success.',
    'People who are crazy enough to think they can change the world, are the ones who do.',
    'Happiness is not something readymade. It comes from your own actions.',
    "Don't judge each day by the harvest you reap but by the seeds that you plant.",
    'The only thing worse than being blind is having sight but no vision.',
    "Find a place inside where there's joy, and the joy will burn out the pain.",
    "Don't take life too seriously. You'll never get out of it alive.",
    "You miss 100% of the shots you don't take.",
    'I alone cannot change the world, but I can cast a stone across the water to create many ripples.',
    'Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.',
    'The best preparation for tomorrow is doing your best today.',
    'Happiness is not by chance, but by choice.',
    'Life changes very quickly, in a very positive way, if you let it.',
    'Keep your eyes on the stars, and your feet on the ground.',
    'It is our choices that show what we truly are, far more than our abilities.',
    'The only impossible journey is the one you never begin.',
    'Only a life lived for others is a life worthwhile.',
    'To handle yourself, use your headto handle others, use your heart.',
    "Everything you've ever wanted is on the other side of fear.",
    'Dream big and dare to fail.',
    'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.',
    'I find that the harder I work, the more luck I seem to have.',
    'Success is not final, failure is not fatal: It is the courage to continue that counts.',
    "It's not whether you get knocked down, it's whether you get up.",
    'You are never too old to set another goal or to dream a new dream.',
    'Never bend your head. Always hold it high. Look the world straight in the eye.',
    'What you get by achieving your goals is not as important as what you become by achieving your goals.',
    'Too many of us are not living our dreams because we are living our fears.',
    'Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.',
    'Remember that not getting what you want is sometimes a wonderful stroke of luck.',
    'The only way to do great work is to love what you do.',
    'If you can dream it, you can achieve it.',
    'The future belongs to those who believe in the beauty of their dreams.',
    'I am not a product of my circumstances. I am a product of my decisions.',
    'Every strike brings me closer to the next home run.',
    'Definiteness of purpose is the starting point of all achievement.',
    "Life is what happens when you're busy making other plans.",
    'We may encounter many defeats but we must not be defeated.',
    'Knowing is not enough; we must apply. Willing is not enough; we must do.',
    'We must let go of the life we have planned, so as to accept the one that is waiting for us.',
    "Don't count the days, make the days count.",
    'The power of imagination makes us infinite.',
    'The best way to predict the future is to invent it.',
    "You miss 100% of the shots you don't take.",
    "Your limitation—it's only your imagination.",
    'Push yourself, because no one else is going to do it for you.',
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    'Dream bigger. Do bigger.',
    "Don't stop when you're tired. Stop when you're done.",
    'Wake up with determination. Go to bed with satisfaction.',
    'Do something today that your future self will thank you for.',
    'Little things make big days.',
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    'Sometimes we can only find our true direction when we let the wind of change carry us.',
    'Dream it. Wish it. Do it.',
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    'Dream bigger. Do bigger.',
    "Don't stop when you're tired. Stop when you're done.",
    'Start where you are. Use what you have. Do what you can.',
    'Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.',
    'He who has a why to live can bear almost any how.',
    'When you feel like quitting, think about why you started.',
    'A diamond is a chunk of coal that did well under pressure.',
    'What we think, we become.',
    'All limitations are self-imposed.',
    'Tough times never last but tough people do.',
    'Problems are not stop signs, they are guidelines.',
    'One day or day one. You decide.',
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    'Work until your idols become your rivals.',
    "Dreams don't work unless you do.",
    "Go the extra mile. It's never crowded there.",
    'Turn your obstacles into opportunities and your problems into possibilities.',
  ]
  private availableSentences: string[] = []

  constructor() {
    this.resetSentences()
  }

  private resetSentences(): void {
    this.availableSentences = [...this.sentences]
  }

  public getNextSentence(): string {
    if (this.availableSentences.length === 0) {
      this.resetSentences()
    }

    const randomIndex = Math.floor(Math.random() * this.availableSentences.length)
    return this.availableSentences.splice(randomIndex, 1)[0]
  }
}
